appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: QBm9Q44PILdb93jZtkiEY2yNlXUFoqXkz49cvLzQGGeCC+s5HTQ3ql05QlfnA3xIYw6aWi8/t5g3BBlb/Brfgzx+K5if7wuUbKspReHX7OkpHYqTAyDD1/EK3g6Um8BVcQyvVOXBFaZzHTCr9hL0mHnDSUiBoPighyooPd1OMxe+diPQi7S2N3FVUTNVeVufP6z8NDyifO29Tq/K/5q1LlhNIw0g20n58u62mYoYmXL5meEaQML+K+Nj+NM1GL8mk7osRoBFqhYmdt3pmyyXG3gd5/Mw5S3x9HXfS3by0loLuPjhA4jAvJS+Vy6xRqjBOl6TJlkMKFhyDQYevTKpECKVF2vpdk+TOFtJ/TuvZz7n49EADVyNqfi4hSb0F2eeePvpx2rfgxdm9y09VJMXvCLkrv4Otbvlqz7spI+U/hiCDdIyTC4OIh6GaJHeaR0/fmINX2iU6TXOULniOBmpulvw4AI0y4Xmv4fKQ71FBJPqrxHbK/joJ8ICT6qXnfnNDw8/yQLFZo0WyPcK4tgFZvnf2IqRSz2npLpJtqLsR3D/3uJLGrhovvuVPiAOhV7Gty0/sn51wJABozU4qdZCiVolO9hG9C0o0AE852oF/0hbq8Q+9hE8LDv7ymyKCPqAE/awYk1A8uGixait19fDjyq/7LLeMgb0Xa0RrcPGwfA=}
